spring:
  application:
    name: support-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/QLDA}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Bangkok
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}

app:
  upload-dir: ${APP_UPLOAD_DIR:uploads}
